Server.Supervisor.start_link()
# IO.inspect Application.start(:mixproject)

Server.Database.create(:pokedex, {:pokemon, "carapuce"})
Server.Database.create(:pokedex, {:dresseur, "pierre"})
IO.inspect Server.Database.read(:pokedex, :pokemon)
IO.inspect Server.Database.read(:pokedex, :dresseur)
Server.Database.update(:pokedex, {:pokemon, "bulbizarre"})
Server.Database.update(:pokedex, {:dresseur, "sacha"})
IO.inspect Server.Database.read(:pokedex, :pokemon)
IO.inspect Server.Database.read(:pokedex, :dresseur)
Server.Database.delete(:pokedex, :pokemon)
Server.Database.delete(:pokedex, :dresseur)
IO.inspect Server.Database.read(:pokedex, :pokemon)
IO.inspect Server.Database.read(:pokedex, :dresseur)
